#
#
#
server:
  port: ${API_PORT_PORT:8989}

# DEBUG
debug: true

# SPRING OPTIONS
spring:
  main:
    banner-mode: off
  graphql:
    graphiql:
      path: /gql
      enabled: true

  datasource:
  liquibase:
    change-log: classpath:/liquibase/changelog.xml

# APP Configurations
app:
  url:
    api:
      v1:
        statistics: /api/v1/statistics
