#
#
#
debug: true

#
server:
  port: ${API_PORT_PORT:8989}

# SPRING OPTIONS
spring:
  main:
    banner-mode: off
  graphql:
    graphiql:
      path: /gql
      enabled: true

  datasource:
#    url: jdbc:h2:file:./db.h2
#    url: jdbc:h2:file:./db.h2;AUTO_SERVER=TRUE
    url: jdbc:h2:tcp://localhost/D:\FL\t\Covid19-API\db.tcp-v2.0.206
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
#  liquibase:
#    enabled: true
#    change-log: "classpath:liquibase/changelog.xml"
#    default-schema: public
#    contexts: dev
#    user: sa
#    password: sa
  h2:
    console:
      enabled: true

  # spring:flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true
    default-schema: "PUBLIC_SCHEMA"
    driver-class-name: org.h2.Driver
    encoding: UTF-8
    url: jdbc:h2:tcp://localhost/D:\FL\t\Covid19-API\db.tcp-v2.0.206
#    url: jdbc:h2:file:./db.h2
    user: sa
    password: sa
    locations: classpath:db/migration


# FLYWAY
flyway:
  url:
  schemas: 'public'
  user: 'sa'
  password: 'sa'


# APP Configurations
app:
  url:
    api:
      v1:
        statistics: /api/v1/statistics
    # url of resources
    src:
      base_url: https://api.covid19api.com
      max_min_statistics: /total/country/%s
      #      max_min_statistics: /premium/country/%s
      username: corona
      auth: ZUav4vawzCfMcMXHV8B
      #      x-access-token: 5cf9dfd5-3449-485e-b5ae-70a60e997864
      x-access-token: c1247632-b1d8-4654-8919-40c1f2709b32
