#
#
#
server:
  port: ${API_PORT_PORT:8989}

# DEBUG
debug: true

# SPRING OPTIONS
spring:
  datasource:

# APP Configurations
app:
  url:
    # url of resources
    src:
      base_url: BASE_URL
      max_min_statistics: PREMIUM_PATH
