#
#
#
debug: false

#
server:
  port: ${API_PORT_PORT:8989}

# SPRING OPTIONS
spring:
  main:
    banner-mode: off
  graphql:
    graphiql:
      path: /gql
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:55433/dev_covid19
    driver-class-name: org.postgresql.Driver
    username: sekretka
    password: sekretka

  # spring:flyway
  flyway:
    enabled: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:55433/dev_covid19
    user: sekretka
    password: sekretka
    schemas: ['public']
    locations: classpath:db/migration
    baseline-on-migrate: true


## FLYWAY
flyway:
  url: jdbc:postgresql://localhost:55433/dev_covid19
  schemas: public
  user: 'sekretka'
  password: 'sekretka'
  locations: 'filesystem:db/migration'

# APP Configurations
app:
  url:
    api:
      v1:
        statistics: /api/v1/statistics
    # url of resources
    src:
      base_url: https://api.covid19api.com
      max_min_statistics: /total/country/%s
      #      max_min_statistics: /premium/country/%s
      username: corona
      auth: ZUav4vawzCfMcMXHV8B
      #      x-access-token: 5cf9dfd5-3449-485e-b5ae-70a60e997864
      x-access-token: c1247632-b1d8-4654-8919-40c1f2709b32
